SampleFileUpload/Models/ErrorViewModel.cs
namespace SampleFileUpload.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SampleFileUpload/Models/FileCreation.cs
using System.ComponentModel.DataAnnotations;

namespace SampleFileUpload.Models
{
    public class FileCreation
    {
        public int Id { get; set; }

        [Display(Name = "File Name")]
        public string FileName { get; set; }

        [Display(Name = "File Type")]
        public string FileType { get; set; }

        [Display(Name = "File Extension")]
        public string Extension { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Uploaded By")]
        public string UploadedBy { get; set; }

        [Display(Name = "Uploaded On")]
        public DateTime UploadedOn { get; set;}

        [Display(Name = "File Path")]
        public string FilePath { get; set; }
    }
}

SampleFileUpload/Controllers/FileUploadController.cs
using Microsoft.AspNetCore.Mvc;
using SampleFileUpload.Data;
using SampleFileUpload.Models;
using SampleFileUpload.ViewModel;

namespace SampleFileUpload.Controllers
{
    public class FileUploadController : Controller
    {
        //Add ApplicationDbContext here
        public readonly ApplicationDbContext _context;
        public FileUploadController(ApplicationDbContext context)
        {
                _context = context;
        }
        [HttpGet]
        public IActionResult Index(FileUploadViewModel vm)
        {
            vm.SystemFiles = new List<FileCreation>();
            return View(vm);
        }

        [HttpPost]
        public IActionResult UploadFile(FileUploadViewModel vm, IFormFile file)
        {
            //var filename = file.FileName;
            var filename = $"{file.FileName}_{DateTime.Now.ToString("yyyymmddhhmmss")}";
            var uploadedfile = new FileCreation
            {
                UploadedOn = DateTime.Now,
                UploadedBy = "Yonela Nuba",
                FileType = file.ContentType,
                FileName = filename,
                Description = vm.Description,
                FilePath = vm.FilePath,
                //Extension = file.

            };
            return View(vm);
        }
    }
}

SampleFileUpload/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SampleFileUpload.Models;
using System.Diagnostics;

namespace SampleFileUpload.Controllers
{
    public class HomeController : Controller
    {

        private readonly IWebHostEnvironment _webHost;
        
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IWebHostEnvironment webHost)
        {
            _logger = logger;
            _webHost = webHost;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Index(IFormFile file)
        {
            string uploadsFolder = Path.Combine(_webHost.WebRootPath,"uploads");

            if(!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }

            string fileName = Path.GetFileName(file.FileName);
            string fileSavePath = Path.Combine(uploadsFolder,fileName);

            using(FileStream stream = new FileStream(fileSavePath, FileMode.Create)) 
            {
                await file.CopyToAsync(stream);
            }

            ViewBag.Message = fileName + " Uploaded successfully!";

            return View();

        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SampleFileUpload/Views/FileUpload/Index.cshtml
@model SampleFileUpload.ViewModel.FileUploadViewModel
@{
    ViewData["Title"] = "Upload File";
}



<div class="text-center">
    <h1 class="display-4">Let's upload a File'</h1>
    <p>We are learning how to upload Files in ASP .NET CORE MVC</p>

</div>
<div class="col-md-12">
    <form method="post" asp-action="UploadFile" enctype="multipart/form-data">
        <div class="row">
    
            <div class="col-md-6">
                <label asp-for="FileName"></label>
                <input type="file" name="file" class="form-control" accept=".jpg, .jpeg, .png" />
            </div>
            <div class="col-md-6">
                <label asp-for="Description"></label>
                <input type="text" class="form-control" />
            </div>
            <div class="col-md-6">
                <input type="submit" value="Upload File" class="btn btn-primary mt-2" />
            </div>
        </div>
    </form>
</div>
<hr />

@if(Model.SystemFiles.Count == 0)
{
    <caption>There are no records in the system!</caption>
}else{
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>@Model.Id</th>
            <th>@Model.FileName</th>
            <th>@Model.FileType</th>
            <th>@Model.Extension</th>
            <th>@Model.UploadedBy</th>
            <th>@Model.UploadedOn</th>
            <th>@Model.Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var file in Model.SystemFiles)
        {
            <tr>
                <td>@file.Id</td>
                <td>@file.FileName</td>
                <td>@file.FileType</td>
                <td>@file.Extension</td>
                <td>@file.UploadedBy</td>
                <td>@file.UploadedOn</td>
                <td>@file.Description</td>
            </tr>
        }
    </tbody>
</table>

            }

SampleFileUpload/Views/FileUpload/Index1.cshtml
@{
    ViewData["Title"] = "Upload File";
}



<div class="text-center">
    <h1 class="display-4">Let's upload a File'</h1>
    <p>We are learning how to upload Files in ASP .NET CORE MVC</p>

</div>
<div class="row">
    <div class="col-md-12">
        <input type="file" class="form-control" accept=".jpg, .jpeg, .png" />
    </div>
</div>

SampleFileUpload/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Upload a File Using MVC</h1>

    <br />
</div>
    
        <form method="post" enctype="multipart/form-data" asp-controller="Home" asp-action="Index">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-6">
                        <input type="file" name="file" class="form-control" accept=".jpg, .jpeg, .png" />
                    </div>            
                    <div class="col-md-6">
                        <input type="submit" value="Upload File" class="btn btn-primary" />
                    </div>
                    <span class="text-success">
                        @ViewBag.Message
                    </span>
                </div>
            </div>
        </form>

   

    

SampleFileUpload/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SampleFileUpload</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SampleFileUpload.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="FileUpload" asp-action="Index">Uploading A File</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FileUpload" asp-action="Index">Upload a File</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sample File Upload - <a asp-area="" asp-controller="Home" asp-action="Privacy">Created by Yonela</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>